local M = {}

function M.get(c, config)
  local util = require("dim-night.util")

  return {
    GitSignsAdd = { fg = c.green_git },
    GitSignsChange = { fg = c.purple },
    GitSignsDelete = { fg = c.red_git },
    GitSignsCurrentLineBlame = { fg = c.gray_dark },

    GitGutterAdd = { fg = c.green_git },
    GitGutterChange = { fg = c.purple },
    GitGutterDelete = { fg = c.red_git },

    TelescopeNormal = { fg = c.fg, bg = c.bg_popup },
    TelescopeBorder = { fg = c.border, bg = c.bg_popup },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_highlight },
    TelescopePromptBorder = { fg = c.border, bg = c.bg_highlight },
    TelescopePromptTitle = { fg = c.bg, bg = c.blue },
    TelescopePromptPrefix = { fg = c.purple },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green },
    TelescopePreviewBorder = { fg = c.border, bg = c.bg_popup },
    TelescopeResultsTitle = { fg = c.bg, bg = c.cyan },
    TelescopeResultsBorder = { fg = c.border, bg = c.bg_popup },
    TelescopeSelection = { bg = c.bg_visual },
    TelescopeSelectionCaret = { fg = c.purple },
    TelescopeMatching = { fg = c.orange, bold = true },

    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.gray, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue, bold = true },
    CmpItemMenu = { fg = c.comment },
    CmpItemKind = { fg = c.cyan },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindColor = { fg = c.green },
    CmpItemKindConstant = { fg = c.yellow },
    CmpItemKindConstructor = { fg = c.blue },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindEnumMember = { fg = c.yellow },
    CmpItemKindEvent = { fg = c.yellow },
    CmpItemKindField = { fg = c.blue_light },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindFunction = { fg = c.orange },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindKeyword = { fg = c.purple },
    CmpItemKindMethod = { fg = c.orange },
    CmpItemKindModule = { fg = c.fg_dark },
    CmpItemKindOperator = { fg = c.fg_dark },
    CmpItemKindProperty = { fg = c.blue_light },
    CmpItemKindReference = { fg = c.red },
    CmpItemKindSnippet = { fg = c.magenta },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.pink_type },
    CmpItemKindUnit = { fg = c.yellow },
    CmpItemKindValue = { fg = c.yellow },
    CmpItemKindVariable = { fg = c.white },

    IndentBlanklineChar = { fg = c.gray_darker },
    IndentBlanklineContextChar = { fg = c.purple },
    IblIndent = { fg = c.gray_darker },
    IblScope = { fg = c.purple },

    NeoTreeNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeNormalNC = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeDimText = { fg = c.gray_dark },
    NeoTreeFileName = { fg = c.fg_sidebar },
    NeoTreeGitAdded = { fg = c.green_bright },
    NeoTreeGitConflict = { fg = c.orange },
    NeoTreeGitDeleted = { fg = c.red_git },
    NeoTreeGitIgnored = { fg = c.gray_dark },
    NeoTreeGitModified = { fg = c.blue_bright },
    NeoTreeGitUntracked = { fg = c.green_bright },
    NeoTreeIndentMarker = { fg = c.gray_darker },
    NeoTreeRootName = { fg = c.fg, bold = true },

    WhichKey = { fg = c.purple },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeperator = { fg = c.comment },
    WhichKeySeparator = { fg = c.comment },
    WhichKeyFloat = { bg = c.bg_sidebar },
    WhichKeyValue = { fg = c.gray },

    BufferLineFill = { bg = c.bg_dark },
    BufferLineBackground = { fg = c.gray, bg = c.bg_dark },
    BufferLineBuffer = { fg = c.gray, bg = c.bg_dark },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg_dark, bg = c.bg },
    BufferLineCloseButton = { fg = c.gray, bg = c.bg_dark },
    BufferLineCloseButtonSelected = { fg = c.red, bg = c.bg },
    BufferLineCloseButtonVisible = { fg = c.gray, bg = c.bg },
    BufferLineIndicatorSelected = { fg = c.purple_dark, bg = c.bg },
    BufferLineSeparator = { fg = c.border, bg = c.bg_dark },
    BufferLineSeparatorSelected = { fg = c.border, bg = c.bg },
    BufferLineSeparatorVisible = { fg = c.border, bg = c.bg },
    BufferLineTab = { fg = c.gray, bg = c.bg_dark },
    BufferLineTabSelected = { fg = c.fg, bg = c.bg },
    BufferLineTabClose = { fg = c.red, bg = c.bg_dark },
    BufferLineModified = { fg = c.orange, bg = c.bg_dark },
    BufferLineModifiedSelected = { fg = c.orange, bg = c.bg },
    BufferLineModifiedVisible = { fg = c.orange, bg = c.bg },

    NotifyERRORBorder = { fg = c.red_error },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.purple },
    NotifyDEBUGBorder = { fg = c.gray },
    NotifyTRACEBorder = { fg = c.magenta },
    NotifyERRORIcon = { fg = c.red_error },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.purple },
    NotifyDEBUGIcon = { fg = c.gray },
    NotifyTRACEIcon = { fg = c.magenta },
    NotifyERRORTitle = { fg = c.red_error },
    NotifyWARNTitle = { fg = c.yellow },
    NotifyINFOTitle = { fg = c.purple },
    NotifyDEBUGTitle = { fg = c.gray },
    NotifyTRACETitle = { fg = c.magenta },
    NotifyBackground = { bg = c.bg },

    MiniIndentscopeSymbol = { fg = c.purple },

    LazyNormal = { fg = c.fg, bg = c.bg_popup },
    LazyButton = { fg = c.fg, bg = c.bg_highlight },
    LazyButtonActive = { fg = c.bg, bg = c.purple },

    MasonNormal = { fg = c.fg, bg = c.bg_popup },

    FlashLabel = { fg = c.bg, bg = c.purple, bold = true },
    FlashBackdrop = { fg = c.gray_dark },
    FlashCurrent = { fg = c.bg, bg = c.yellow },

    NoiceCmdlinePopup = { fg = c.fg, bg = c.bg_popup },
    NoiceCmdlinePopupBorder = { fg = c.border },
    NoiceCmdlineIcon = { fg = c.purple },

    TroubleNormal = { fg = c.fg, bg = c.bg_sidebar },

    SnacksNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    SnacksNormalNC = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    SnacksDashboardNormal = { fg = c.fg, bg = c.bg },
    SnacksNotifierBorder = { fg = c.border, bg = c.bg_popup },
    SnacksNotifierInfo = { fg = c.purple },
    SnacksNotifierWarn = { fg = c.yellow },
    SnacksNotifierError = { fg = c.red_error },
    SnacksNotifierDebug = { fg = c.gray },
  }
end

return M
